name: build-ios-app

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Upload app to AppStore
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - run: fastlane release
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PAT: ${{ secrets.PAT }}
          APP_ID: ${{ secrets.APP_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_KEY }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
